export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILD = "USER_LOGIN_FAILD";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_VERIFY_REQUEST="USER_VERIFY_REQUEST";
export const USER_VERIFY_SUCCESS="USER_VERIFY_SUCCESS";
export const USER_VERIFY_FAILD="USER_VERIFY_FAILD";